### ISSUE TITLE
How to train a NMT model ?

### ISSUE THREAD

**Issue by kobenaxie** [yaserkl/RLSeq2Seq#12]
As for a NMT task, with this code, whther it means I just need to replace the data[for summarization task ] with the data for NMT task, like WMT14 ?

**Comment by yaserkl** [comment]
For NMT, you have to make sure that you are not using the pointer generator since it's not the right choice for training a machine translation. What you end up after deactivating pointer-generator is a simple seq2seq attention based model which is not gonna give you the state-of-the-art results in this specific task. Since this library doesn't have modules for Transformer unit (which currently yields the state-of-the-art results in NMT), I would suggest to try to work on projects like tensor2tensor and add RL training the way that I did in this project.

**Comment by kobenaxie** [comment]
OK, thank you for your suggestion ~
