### ISSUE TITLE
Question about the implementation of self-critic policy gradient reinforcement learning  

### ISSUE THREAD

**Issue by weili-ict** [yaserkl/RLSeq2Seq#16]
Hi, thanks very much for sharing the excellent code, which is really helpful for my research.

I have some questions about your implementation of the self-critic policy gradient reinforcement learning algorithm on seq2seq models.

I note that, you obtain the sample sequence and greedy sequence with ground truth input in each decoding step in the attention_decoder.py (line 407-413).  However, does the decoder should use the previous token in the sample sequence or greedy sequence as input in each decoding step?

Looking forward to your reply! Thanks!

**Comment by yaserkl** [comment]
Yes, during policy gradient RL we have to use the sampled sentence as the input rather than ground-truth that's why we provided scheduled sampling mechanism in this library. Therefore, during RL training a good practice is to activate scheduled sampling by setting "scheduled_sampling" parameter to True and set the "sampling_probability" and "fixed_sampling_probability" parameters to 1.0 and True, respectively so that model input completely comes from the sampled sentence rather than ground-truth.
Moreover, if you want to gradually increase the scheduled sampling during your training, you can set "fixed_sampling_probability" parameter to False and start with a low "sampling_probability". The model will increase this probability linearly such that for instance if you want your model to be trained 1000 time, setting this parameter to 1E-03 will tell the model to sample from sampled sentence with probability 1E-03 in the beginning of the training but as we get to iteration 1000, sample with probability 1000*1E-03=1.

**Comment by weili-ict** [comment]
Thanks for your kind reply @yaserkl . It helps me a lot.

I think the "scheduled_sampling" is a wonderful design. However, the decoder will do sampling twice in each decoding step during RL training: one is for generating the input (line 331-334 in attention_decoder.py), another is for generating the sample sequence (line 407-410). How do you guarantee the two sampling operation get the same sample_ids, since the input must be the previous token in the sample sequence? 

I think directly use the k_sample (line 410) as the next input during RL training is a better choice. What's your opinion ?

Looking forward to your reply! Thanks!

**Comment by yaserkl** [comment]
To answer your first question, since at each step of decoding, we only sample one token (either in line 331 or line 407) and our sampler has a specific seed value, it guarantees that we get the same token in both lines. However, I believe that this could be better designed to do the sampling once to make it less confusing.
Regarding your second question, the greedy selection during training should be taken from the same distribution that we use for sampling. Therefore, it is not required to pass a separate token chosen by greedy selection from previous decoder unit to select our greedy sentence. This will make the back-propagation of error very confusion since model would then require to back-propagate twice, one for the sequence selected by only sampling and again for sequence selected by greedy. To ease all this, we choose two different tokens at each decoding step: a greedy token and a sampling one, and feed the sampling one to the next decoder as input during scheduled sampling.

**Comment by weili-ict** [comment]
Thank you very much for answering my questions tirelessly @yaserkl.

Its't a great idea to choose the sampling token as input to generate both the sample sequence and greedy sequence. I got bad results when using sampling token as input for generating the sample sequence and greedy token as input for the greedy sequence separately.
