### ISSUE TITLE
Transfer learning

### ISSUE THREAD

**Issue by nickluijtgaarden** [yaserkl/RLSeq2Seq#26]
Dear Yaser,

My name is Nick and I am currently writing my thesis on abstractive summarization. More specifically, I am looking into applying transfer learning on a legal domain dataset. My current approach is around using transfer learning on a larger, more general dataset in order to pre-train a neural network.

With great enthusiasm I read your paper (Deep Transfer Reinforcement Learning for Text Summarization) and I think your approach looks really interesting. The thing I like most is your RL approach to increase the generalization power of the model. In your paper you discuss how you used the RLSeq2Seq framework and build your model on top of it.

Do you have a protoype of your model and how it can be used? In your work, you refer to the model on www.github.com/yaserkl/TransferRL, but this link seems to be broken.

**Comment by yaserkl** [comment]
Hi,
Thanks for showing an interest in our research.
Unfortunately, due to using this model in our internal ongoing project with one of the Virginia Tech third parties, we had to remove the code from public access.

I have updated the arxiv paper and removed the link from the final version.
We will push for publishing the code in the near future, but until now we cannot legally do it.

**Comment by yaserkl** [comment]
@nickluijtgaarden I just release the code for the TransferRL paper.
