### ISSUE TITLE
Evaluation results in comparison to Seq2Seq without RL

### ISSUE THREAD

**Issue by shahbazsyed** [yaserkl/RLSeq2Seq#3]
Hi,
Good work and thanks for sharing the code!
Can you kindly provide some results of comparing your model with a base Seq2Seq model with attention on text summarization task for example? I see that an evaluation section with scores for various metrics is not present in the paper.

**Comment by yaserkl** [comment]
Yes, we will release some of the results with basic models, soon. But, due to our computing shortage (only accessing to a couple of GPUs) they might take some time. We strongly encourage others to run their own experiments and share the results with community.
For now,  we are only working with CNN/DM dataset since Newsroom dataset is 10 times larger than this.
